POST http://localhost:3000/api/tarefas
Content-Type: application/json

{
  "titulo": "Nova Tarefa",
  "descricao": "Descrição da nova tarefa"
}

###
DELETE http://localhost:3000/api/tarefas/1

###
PATCH http://localhost:3000/api/tarefas/9
Content-Type: application/json

{
  "estaCompleta": false
}